In [5]:
import pandas as pd

In [6]:
brands_df = pd.read_csv("data/raw/brands.csv")

In [7]:
brands_df

    short       long
0     8MO  8Mobility
1     ACM       Acme
2     ADN     Adonit
3     AII      Aiino
4     AKI     Akitio
..    ...        ...
182   XOO     Xoopar
183   XRI     X-Rite
184   XTO      Xtorm
185   ZAG   ZaggKeys
186   ZEP       Zepp

[187 rows x 2 columns]

In [8]:
brands_df[brands_df["long"].duplicated(keep=False)]

    short      long
6     AP2     Apple
7     APP     Apple
17    BOS      Bose
19    CAD      Bose
37    ENV   Unknown
67    JYB   Jaybird
70    KEN   Jaybird
80    LIB   Unknown
94    MOP    Mophie
98    MUJ    Mophie
117   OTR  Startech
153   STA  Startech

TODO: check for every duplicate which one is more used and replace the short in the sku. then drop the less used duplicates -> Yahya