In [1]:
import pandas as pd

In [2]:
full_df = pd.read_csv("data/processed/full_df.csv")

In [3]:
full_df

,order_id,created_date,total_paid,state,sku,name,desc,price,in_stock,type,id,product_quantity,unit_price,orderlines_date,median_price,price_ratio,false_price,ratio,short,long
0,299539,2017-01-01 00:07:19,18.99,Shopping Basket,OTT0133,Otterbox iPhone Case Symmetry 2.0 SE / 5s / 5 ...,resistant cover and thin beveled edges for iPh...,34.99,0.0,11865403.0,1119109,1,18.99,2017-01-01 00:07:19,19.990,0.949975,False,1.75,OTT,Otterbox
1,299540,2017-01-01 00:19:45,399.00,Shopping Basket,LGE0043,"27UD58-B LG Monitor 27 ""4K UHD DisplayPort",Monitor for gamers and multimedia professional...,429.00,0.0,1296.0,1119110,1,399.00,2017-01-01 00:19:45,375.000,1.064000,False,1.14,LGE,LG
2,299541,2017-01-01 00:20:57,474.05,Shopping Basket,PAR0071,Parrot Bebop 2 White + Command FLYPAD and FPV ...,cuadricóptero wireless remote control with 25 ...,699.00,0.0,11905404.0,1119111,1,474.05,2017-01-01 00:20:57,561.980,0.843535,False,1.24,PAR,Parrot
3,299542,2017-01-01 00:51:40,68.39,Shopping Basket,WDT0315,"Blue WD 2TB Hard Drive 35 ""Mac and PC",Internal Hard Drive Western Digital 2TB 3.5-in...,79.00,0.0,12655397.0,1119112,1,68.39,2017-01-01 00:51:40,70.785,0.966165,False,1.12,WDT,Western Digital
4,299543,2017-01-01 01:06:38,23.74,Shopping Basket,JBL0104,Gray Bluetooth Speaker JBL GO,Compact Bluetooth Handsfree for iPhone iPad an...,29.90,1.0,5398.0,1119113,1,23.74,2017-01-01 01:06:38,24.490,0.969375,True,1.22,JBL,JBL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285434,527397,2018-03-14 13:56:38,42.99,Place Order,JBL0122,JBL T450 BT Bluetooth Headset Black,Wireless headphones with folding design with 1...,49.95,1.0,5384.0,1650198,1,42.99,2018-03-14 13:56:38,42.990,1.000000,False,1.16,JBL,JBL
285435,527398,2018-03-14 13:57:25,42.99,Shopping Basket,JBL0122,JBL T450 BT Bluetooth Headset Black,Wireless headphones with folding design with 1...,49.95,1.0,5384.0,1650199,1,42.99,2018-03-14 13:57:25,42.990,1.000000,False,1.16,JBL,JBL
285436,527399,2018-03-14 13:57:34,141.58,Shopping Basket,PAC0653,Samsung SSD 850 expansion kit EVO 250GB + Data...,SSD upgrade kit 2008-2010 250 GB MacBook and M...,215.98,1.0,1433.0,1650200,1,141.58,2018-03-14 13:57:34,151.660,0.933536,False,1.42,PAC,Pack
285437,527400,2018-03-14 13:57:41,19.98,Shopping Basket,APP0698,Apple Lightning Cable Connector to USB 1m Whit...,Apple Lightning USB Cable 1 meter to charge an...,25.00,1.0,1230.0,1650201,2,9.99,2018-03-14 13:57:41,9.990,1.000000,False,2.50,APP,Apple
285438,527401,2018-03-14 13:58:36,18.98,Place Order,APP0927,EarPods Apple Headphones with Remote and Mic (...,EarPods headphones Apple iPhone iPad and iPod ...,35.00,1.0,5384.0,1650203,1,13.99,2018-03-14 13:58:36,17.090,0.818607,False,2.05,APP,Apple

In [4]:
# only orders with state Completed
completed_orders = full_df.loc[full_df["state"] == "Completed"]

In [6]:
completed_orders

,order_id,created_date,total_paid,state,sku,name,desc,price,in_stock,type,id,product_quantity,unit_price,orderlines_date,median_price,price_ratio,false_price,ratio,short,long
7,299545,2017-01-01 01:51:47,51.48,Completed,OWC0100,OWC In-line Digital Temperature Sensor Kit HDD...,Kit temperature sensor for HDD iMac 21 inch an...,60.99,1.0,12755395.0,1119116,1,47.49,2017-01-01 01:46:16,49.99,0.949990,False,1.22,OWC,OWC
8,299546,2017-01-01 01:57:34,18.99,Completed,IOT0014,iOttie Easy View 2 Car Black Support,IPhone car holder 7 plus / 7/6 Plus / 6 / 5s /...,22.95,0.0,5720.0,1119119,1,18.99,2017-01-01 01:50:34,16.99,1.117716,False,1.35,IOT,iOttie
9,295347,2017-01-01 02:02:38,72.19,Completed,APP0700,Apple 85W MagSafe 2 charger MacBook Pro screen...,Apple MagSafe 2 Charger for MacBook Pro 15-inc...,89.00,1.0,13005399.0,1119120,1,72.19,2017-01-01 01:54:11,69.99,1.031433,False,1.27,APP,Apple
11,299549,2017-01-02 10:00:20,2565.99,Completed,PAC0929,"Apple iMac 27 ""Core i5 3.2GHz Retina 5K | 32GB...",IMac desktop computer 27 inch Retina 5K RAM 32...,3209.00,0.0,1282.0,1119126,1,2565.99,2017-01-01 02:07:42,2667.99,0.961769,False,1.20,PAC,Pack
18,299556,2017-01-01 02:30:08,65.89,Completed,CRU0039-A,(Open) Crucial 240GB SSD 7mm BX200,SSD hard drive and high-speed performance with...,76.99,0.0,1298.0,1119134,1,60.90,2017-01-01 02:20:14,60.90,1.000000,False,1.26,CRU,Crucial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285059,525664,2018-03-14 11:56:19,85.73,Completed,TUC0207,Tucano Elements Second Skin Macbook Sleeve 12 ...,velvety inner protective case for MacBook 12 i...,24.99,0.0,13835403.0,1649474,1,16.52,2018-03-14 11:45:05,19.99,0.826413,False,1.25,TUC,Tucano
285076,527070,2018-03-14 11:50:48,24.97,Completed,APP0698,Apple Lightning Cable Connector to USB 1m Whit...,Apple Lightning USB Cable 1 meter to charge an...,25.00,1.0,1230.0,1649512,2,9.99,2018-03-14 11:49:01,9.99,1.000000,False,2.50,APP,Apple
285081,527074,2018-03-14 11:51:42,24.97,Completed,APP0698,Apple Lightning Cable Connector to USB 1m Whit...,Apple Lightning USB Cable 1 meter to charge an...,25.00,1.0,1230.0,1649522,2,9.99,2018-03-14 11:49:36,9.99,1.000000,False,2.50,APP,Apple
285104,527096,2018-03-14 11:58:40,34.96,Completed,APP0698,Apple Lightning Cable Connector to USB 1m Whit...,Apple Lightning USB Cable 1 meter to charge an...,25.00,1.0,1230.0,1649565,3,9.99,2018-03-14 11:54:35,9.99,1.000000,False,2.50,APP,Apple
285120,527112,2018-03-14 12:03:52,14.98,Completed,APP0698,Apple Lightning Cable Connector to USB 1m Whit...,Apple Lightning USB Cable 1 meter to charge an...,25.00,1.0,1230.0,1649593,1,9.99,2018-03-14 11:58:13,9.99,1.000000,False,2.50,APP,Apple

In [8]:
completed_orders[["state", "name"]].groupby("state").count()

            name
state
Completed  60219