In [1]:
import pandas as pd

In [2]:
brands_df = pd.read_csv("data/raw/brands.csv")
orderlines_df = pd.read_csv("data/raw/orderlines.csv")
orders_df = pd.read_csv("data/raw/orders.csv")
products_df = pd.read_csv("data/raw/products.csv")

In [3]:
brands_df

    short       long
0     8MO  8Mobility
1     ACM       Acme
2     ADN     Adonit
3     AII      Aiino
4     AKI     Akitio
..    ...        ...
182   XOO     Xoopar
183   XRI     X-Rite
184   XTO      Xtorm
185   ZAG   ZaggKeys
186   ZEP       Zepp

[187 rows x 2 columns]

In [4]:
brands_df = brands_df.rename(columns = {"short" : "short", "long" : "long"})

In [5]:
brands_df

    short       long
0     8MO  8Mobility
1     ACM       Acme
2     ADN     Adonit
3     AII      Aiino
4     AKI     Akitio
..    ...        ...
182   XOO     Xoopar
183   XRI     X-Rite
184   XTO      Xtorm
185   ZAG   ZaggKeys
186   ZEP       Zepp

[187 rows x 2 columns]

In [6]:
orderlines_df

,id,id_order,product_id,product_quantity,sku,unit_price,date
0,1119109,299539,0,1,OTT0133,18.99,2017-01-01 00:07:19
1,1119110,299540,0,1,LGE0043,399.00,2017-01-01 00:19:45
2,1119111,299541,0,1,PAR0071,474.05,2017-01-01 00:20:57
3,1119112,299542,0,1,WDT0315,68.39,2017-01-01 00:51:40
4,1119113,299543,0,1,JBL0104,23.74,2017-01-01 01:06:38
...,...,...,...,...,...,...,...
293978,1650199,527398,0,1,JBL0122,42.99,2018-03-14 13:57:25
293979,1650200,527399,0,1,PAC0653,141.58,2018-03-14 13:57:34
293980,1650201,527400,0,2,APP0698,9.99,2018-03-14 13:57:41
293981,1650202,527388,0,1,BEZ0204,19.99,2018-03-14 13:58:01
293982,1650203,527401,0,1,APP0927,13.99,2018-03-14 13:58:36

In [7]:
orderlines_df.nunique()

id                  293983
id_order            204855
product_id               1
product_quantity        67
sku                   7951
unit_price           11329
date                251631
dtype: int64

In [8]:
orderlines_df = orderlines_df.drop("product_id", axis = 1)

In [9]:
orderlines_df

,id,id_order,product_quantity,sku,unit_price,date
0,1119109,299539,1,OTT0133,18.99,2017-01-01 00:07:19
1,1119110,299540,1,LGE0043,399.00,2017-01-01 00:19:45
2,1119111,299541,1,PAR0071,474.05,2017-01-01 00:20:57
3,1119112,299542,1,WDT0315,68.39,2017-01-01 00:51:40
4,1119113,299543,1,JBL0104,23.74,2017-01-01 01:06:38
...,...,...,...,...,...,...
293978,1650199,527398,1,JBL0122,42.99,2018-03-14 13:57:25
293979,1650200,527399,1,PAC0653,141.58,2018-03-14 13:57:34
293980,1650201,527400,2,APP0698,9.99,2018-03-14 13:57:41
293981,1650202,527388,1,BEZ0204,19.99,2018-03-14 13:58:01
293982,1650203,527401,1,APP0927,13.99,2018-03-14 13:58:36

In [10]:
orderlines_df.columns = ["id", "order_id", "product_quantity", "sku", "unit_price", "order_date"]

In [11]:
orders_df

        order_id         created_date  total_paid            state
0         241319  2017-01-02 13:35:40       44.99        Cancelled
1         241423  2017-11-06 13:10:02      136.15        Completed
2         242832  2017-12-31 17:40:03       15.76        Completed
3         243330  2017-02-16 10:59:38       84.98        Completed
4         243784  2017-11-24 13:35:19      157.86        Cancelled
...          ...                  ...         ...              ...
226904    527397  2018-03-14 13:56:38       42.99      Place Order
226905    527398  2018-03-14 13:57:25       42.99  Shopping Basket
226906    527399  2018-03-14 13:57:34      141.58  Shopping Basket
226907    527400  2018-03-14 13:57:41       19.98  Shopping Basket
226908    527401  2018-03-14 13:58:36       18.98      Place Order

[226909 rows x 4 columns]

In [12]:
products_df = products_df.drop_duplicates()
products_df

,sku,name,desc,price,promo_price,in_stock,type
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,499.899,1,8696
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59,589.996,0,13855401
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59,569.898,0,1387
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25,229.997,0,1230
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pr...,34.99,31.99,1,1364
...,...,...,...,...,...,...,...
19321,BEL0376,Belkin Travel Support Apple Watch Black,compact and portable stand vertically or horiz...,29.99,269.903,1,12282
19322,THU0060,"Enroute Thule 14L Backpack MacBook 13 ""Black",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392
19323,THU0061,"Enroute Thule 14L Backpack MacBook 13 ""Blue",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392
19324,THU0062,"Enroute Thule 14L Backpack MacBook 13 ""Red",Backpack with capacity of 14 liter compartment...,69.95,649.903,0,1392
19325,THU0063,"Enroute Thule 14L Backpack MacBook 13 ""Green",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392

In [13]:
products_df[products_df["sku"].duplicated(keep=False)]
# products_df.drop(8000)

,sku,name,desc,price,promo_price,in_stock,type
7992,APP1197,"Apple iMac 21.5 ""Core i5 31 GHz Retina display...",Desktop Apple iMac 21.5 inch i5 31 GHz Retina ...,1729,1305.59,0,1282
8000,APP1197,"Apple iMac 21.5 ""Core i5 31 GHz Retina display...",Desktop Apple iMac 21.5 inch i5 31 GHz Retina ...,NaN,1305.59,0,1282

TODO:
price and promo_price to float
compare price and promo_price

In [14]:
mask = pd.to_numeric(products_df["price"], errors="coerce").isna()
products_df[mask]

,sku,name,desc,price,promo_price,in_stock,type
34,TWS0019,Twelve South MagicWand support Apple Magic Tra...,MagicWand for wireless keyboard and Magic Trac...,NaN,299.899,0,8696
665,CRU0015-2,Crucial memory Mac 16GB (2x8GB) SO-DIMM DDR3 1...,RAM 16GB (2x8GB) 135V MacBook Pro iMac (2012/2...,1.639.792,1.629.894,1,1364
792,APP0672,Apple iPhone 5S 16GB Space Gray,New iPhone 5S 16G Libre (ME432Y / AB).,4.694.994,4.694.994,0,NaN
797,APP0673,Apple iPhone 5S 16GB Silver,New Free iPhone 5S 16GB (ME433Y / A).,4.090.042,4.090.042,0,NaN
827,PAC0339,NewerTech miniStack 4TB Hard Drive Mac,External Box Hard Drive Mac + 4TB.,2.199.791,2.199.901,0,11935397
...,...,...,...,...,...,...,...
19312,REP0424,Input repair Headphones iPad,Repair service including parts and labor for iPad,6.999.003,69.99,0,"1,44E+11"
19313,REP0421,iPad charging connector repair,Repair service including parts and labor for iPad,6.999.003,69.99,0,"1,44E+11"
19314,REP0416,iPad front camera repair,Repair service including parts and labor for iPad,6.999.003,69.99,0,"1,44E+11"
19315,REP0413,repair rear camera iPad,Repair service including parts and labor for iPad,6.999.003,69.99,0,"1,44E+11"
19316,REP0407,iPad battery repair,Repair service including parts and labor for iPad,6.999.003,69.99,0,"1,44E+11"

In [15]:
# products_df["price"] = products_df["price"].str.replace(".", "")

In [17]:
order_check = (
    orders_df.loc[orders_df["order_id"].isin([427314, 431655, 447411, 448966, 449596])]
    .merge(orderlines_df, left_on="order_id", right_on="order_id")
    .merge(products_df, on="sku")
)
order_check.head()

,order_id,created_date,total_paid,state,id,product_quantity,sku,unit_price,order_date,name,desc,price,promo_price,in_stock,type
0,427314,2017-11-20 18:54:39,NaN,Pending,1416957,1,MUJ0023,26.99,2017-11-20 18:40:45,Mujjo Leather Leather iPhone Case 8 Plus / 7 P...,ultrafine material cover with vegetable tanned...,44.9,269.891,0,11865403
1,427314,2017-11-20 18:54:39,NaN,Pending,1416966,1,APP1696,49.00,2017-11-20 18:44:30,Leather Case Cover Apple iPhone 7 Plus Blue Sea,ultrathin leather case and microfiber premium ...,59,51,0,11865403
2,431655,2017-11-22 12:15:24,NaN,Pending,1421402,1,APP1922,154.00,2017-11-22 12:12:16,AirPods Apple Bluetooth Headset for iPhone iPa...,Apple AirPods wireless headsets and cargo tran...,179,1.610.001,1,5384
3,447411,2017-11-27 10:32:37,NaN,Pending,1456182,1,LAC0225,180.76,2017-11-27 10:30:28,Lacie Rugged Hard Drive 2TB USB-C Thunderbolt,"2TB hard drive rugged, compact Thunderbolt and...",209.99,1.699.941,0,11935397
4,448966,2017-11-27 18:54:15,NaN,Pending,1459674,1,PAC2266,961.02,2017-11-27 18:03:18,Synology DS918 + NAS Server | 8GB | 8TB (4x2TB...,NAS server of the Plus Series for companies se...,1032.98,9.753.677,0,12175397