In [80]:
import pandas as pd

In [81]:
brands_df = pd.read_csv("data/raw/brands.csv")
orderlines_df = pd.read_csv("data/processed/orderlines.csv")
orders_df = pd.read_csv("data/processed/orders.csv")
products_df = pd.read_csv("data/processed/products.csv")

In [82]:
products_df["short"] = products_df["sku"].str[0:3]

In [83]:
full_df = products_df.merge(brands_df, on = "short", how = "left")

In [84]:
full_df = full_df.drop("short", axis = 1)

In [85]:
full_df = full_df.rename(columns = {"long": "brand"})

In [86]:
full_df

,sku,name,desc,price,in_stock,type,brand
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,1,8696.0,Rain Design
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59.00,0,13855401.0,Apple
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59.00,0,1387.0,Apple
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25.00,0,1230.0,Apple
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pr...,34.99,1,1364.0,Kingston
...,...,...,...,...,...,...,...
10529,BEL0376,Belkin Travel Support Apple Watch Black,compact and portable stand vertically or horiz...,29.99,1,12282.0,Belkin
10530,THU0060,"Enroute Thule 14L Backpack MacBook 13 ""Black",Backpack with capacity of 14 liter compartment...,69.95,1,1392.0,Thule
10531,THU0061,"Enroute Thule 14L Backpack MacBook 13 ""Blue",Backpack with capacity of 14 liter compartment...,69.95,1,1392.0,Thule
10532,THU0062,"Enroute Thule 14L Backpack MacBook 13 ""Red",Backpack with capacity of 14 liter compartment...,69.95,0,1392.0,Thule
10533,THU0063,"Enroute Thule 14L Backpack MacBook 13 ""Green",Backpack with capacity of 14 liter compartment...,69.95,1,1392.0,Thule

In [87]:
orderlines_df

,id,order_id,product_quantity,sku,unit_price,orderlines_date
0,1119109,299539,1,OTT0133,18.99,2017-01-01 00:07:19
1,1119110,299540,1,LGE0043,399.00,2017-01-01 00:19:45
2,1119111,299541,1,PAR0071,474.05,2017-01-01 00:20:57
3,1119112,299542,1,WDT0315,68.39,2017-01-01 00:51:40
4,1119113,299543,1,JBL0104,23.74,2017-01-01 01:06:38
...,...,...,...,...,...,...
293978,1650199,527398,1,JBL0122,42.99,2018-03-14 13:57:25
293979,1650200,527399,1,PAC0653,141.58,2018-03-14 13:57:34
293980,1650201,527400,2,APP0698,9.99,2018-03-14 13:57:41
293981,1650202,527388,1,BEZ0204,19.99,2018-03-14 13:58:01
293982,1650203,527401,1,APP0927,13.99,2018-03-14 13:58:36

In [88]:
full_df = orderlines_df.merge(full_df, on = "sku", how = "outer")

In [89]:
full_df = orders_df.merge(full_df, on = "order_id", how = "outer")

In [90]:
full_df.to_csv("data/processed/full_df.csv", index = False)

In [91]:
full_df_test = full_df[["sku", "name", "price", "unit_price"]].sample(50)

In [92]:
full_df.loc[full_df["sku"] == "REP0043"]

,order_id,created_date,total_paid,state,id,product_quantity,sku,unit_price,orderlines_date,name,desc,price,in_stock,type,brand
318324,NaN,NaN,NaN,NaN,NaN,NaN,REP0043,NaN,NaN,Speaker lower repair iPhone 4,Repair service including parts and labor for i...,49.9,0.0,1.440000e+11,Repair

In [93]:
full_df[["sku", "name", "price", "unit_price"]].sample(100)

,sku,name,price,unit_price
157702,NTE0045,NewerTech NuGuard KX iPhone Case SE / 5s / 5 B...,60.99,11.15
174068,APP1921,Apple USB Power Adapter-C 87 W for MacBook Pro...,89.00,77.39
105972,APP2012,Apple iPad Smart Cover Case Charcoal Gray,45.00,39.00
126664,IKM0063,IK Multimedia iRig Nano Amp Amplifier,60.99,45.98
219064,MIN0011,Minibatt iCharger Qi Wireless Charger Quick ch...,15.90,13.99
...,...,...,...,...
69566,MUV0183,Muvit iPhone Folio 7 / 6s / 6 White / Transparent,13.95,10.99
4012,APP1190,IPhone AppleCare Protection Plan,70.00,62.99
45346,APP1215,Spanish Keyboard Keyboard Magic Apple Mac,119.00,98.35
305281,APP0698,Apple Lightning Cable Connector to USB 1m Whit...,25.00,10.99
190552,MOS0237,Moshi Vitros X Transparent Silver iPhone Case,25.00,19.99